# Generated by Django 2.2.10 on 2020-05-20 04:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20200519_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
